services:
  app:
    build: .
    container_name: trend_antenna_app
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports
    network_mode: host

  mongodb:
    image: mongo:7
    container_name: trend_antenna_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
