services:
  app:
    build: .
    container_name: trend_antenna_app
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports
    depends_on:
      - mongodb
    networks:
      - trend_antenna_network

  mongodb:
    image: mongo:7
    container_name: trend_antenna_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - trend_antenna_network

networks:
  trend_antenna_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
